development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:812c033cc708144413bd24fce9eccaaf@grouper.redistogo.com:11591/
  channel_prefix: project-3_production
